<%@ Page Language="VB" MasterPageFile="~/MasterPage.master" AutoEventWireup="false" CodeFile="componentMaster.aspx.vb" Inherits="maintenance_componentMaster" %>
<asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <table border="0">
        <tr>
            <td>
                Add new Master Type:
            </td>
            <td>
                <asp:TextBox ID="txtNewType" runat="server" OnTextChanged="txtNewType_textChanged" MaxLength="50" AutoPostBack="true"></asp:TextBox> <asp:Button ID="btnSubmit" runat="server" Text="Add" OnClick="btnSubmit_click" />
            </td>
        </tr>
        <tr>
            <td colspan="2">&nbsp;</td>
        </tr>
        <tr>
            <td colspan="2">
                <asp:Label ID="lblDeleteError" runat="server" ForeColor="red"></asp:Label>
            </td>
        </tr>
        <tr>
            <td valign="top">
                Current Master Types:
            </td>
            <td>
                <asp:GridView ID="gvMaster" runat="server" DataKeyNames="masterID" SkinID="GridView" AutoGenerateColumns="false" ShowHeader="true" DataSourceID="sqlProductMaster" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" EmptyDataText="None set up yet." GridLines="none" BorderWidth="0">
                <Columns>
                    <asp:BoundField ItemStyle-Width="20" ReadOnly="true" />
                    <asp:BoundField HeaderText="Type" DataField="name" ItemStyle-Width="140" />
                    <asp:CheckBoxField HeaderText="Active" DataField="active" ItemStyle-HorizontalAlign="Center" />
                </Columns>
            </asp:GridView>
            </td>
        </tr>
    </table>
     
   
    
    <asp:SqlDataSource ID="sqlProductMaster" runat="server" SelectCommand="procComponentMastersSelect" SelectCommandType="StoredProcedure" DeleteCommand="procComponentMasterByMasterIDDelete" DeleteCommandType="StoredProcedure" ConnectionString="<%$ ConnectionStrings:connectionString %>" UpdateCommand="procComponentMasterByMasterIDUpdate" UpdateCommandType="StoredProcedure" OnDeleting="sqlProductMaster_deleting">
        <DeleteParameters>
            <asp:Parameter Name="masterID" Type="int32" />
        </DeleteParameters>
        <UpdateParameters>
            <asp:Parameter Name="masterID" Type="int32" />
            <asp:Parameter Name="name" Type="String" />
            <asp:Parameter Name="active" Type="boolean" />
        </UpdateParameters>
    </asp:SqlDataSource>
</asp:Content>

